README.md, src/main/java/io/jaconi/morp/SecurityConfiguration.java, src/main/resources/application.yaml
=> fix: expose and document prometheus metrics

README.md, src/main/resources/.gitignore, src/main/resources/application-dev.yaml
Issue URL:
-
-
<hr />
❤️ Thank you!
=> feat: add dev profile

build.gradle.kts, src/main/java/io/jaconi/morp/MorpApplication.java, src/main/java/io/jaconi/morp/oauth/ClientRegistrationFetcher.java, src/main/java/io/jaconi/morp/oauth/ClientRegistrationSource.java, src/main/java/io/jaconi/morp/oauth/ProviderResolver.java, src/main/java/io/jaconi/morp/oauth/RegistrationResolver.java, src/main/java/io/jaconi/morp/oauth/SimpleOAuth2Properties.java, src/main/java/io/jaconi/morp/oauth/TenantAwareClientRegistrationRepository.java, src/main/java/io/jaconi/morp/tenant/TenantService.java, src/main/resources/application.yaml, src/test/java/io/jaconi/morp/MorpApplicationTests.java, src/test/java/io/jaconi/morp/MorpReactiveUserServiceTest.java, src/test/java/io/jaconi/morp/oauth/ProviderResolverTest.java, src/test/java/io/jaconi/morp/oauth/RegistrationResolverTest.java, src/test/java/io/jaconi/morp/oauth/TenantAwareClientRegistrationRepositoryTest.java, src/test/java/io/jaconi/morp/tenant/TenantServiceTest.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> Client Registration Persistence

build.gradle.kts, src/main/java/io/jaconi/morp/GatewayHints.java, src/main/java/io/jaconi/morp/MorpApplication.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: fix native image

src/integrationTest/java/io/jaconi/morp/SeleniumIT.java, src/integrationTest/resources/application-selenium.yaml
Issue URL:
-
-
<hr />
❤️ Thank you!
=> test: extend selenium test with host based tenant identification

build.gradle.kts
Issue URL:
-
-
<hr />
❤️ Thank you!
=> build: disable module-based generator for now

.releaserc
Issue URL:
-
-
<hr />
❤️ Thank you!
=> ci: fix Docker compose version replacement

src/main/java/io/jaconi/morp/oauth/ClientRegistrationFetcher.java, src/main/java/io/jaconi/morp/oauth/RegistrationResolver.java, src/main/java/io/jaconi/morp/oauth/SimpleOAuth2Properties.java, src/test/java/io/jaconi/morp/oauth/ClientRegistrationFetcherTest.java, src/test/java/io/jaconi/morp/oauth/RegistrationResolverTest.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: add sensible defaults

src/test/java/io/jaconi/morp/RoutingTest.java, src/test/resources/application-test.yaml
Issue URL:
-
-
<hr />
❤️ Thank you!
=> test: added tests to show unexpected response codes

src/integrationTest/java/io/jaconi/morp/ProxyIT.java, src/integrationTest/java/io/jaconi/morp/SeleniumIT.java, src/main/java/io/jaconi/morp/SecurityConfiguration.java, src/main/java/io/jaconi/morp/filters/RemoveSessionCookieFilter.java, src/main/resources/application.yaml, src/test/java/io/jaconi/morp/filters/RemoveSessionCookieFilterTest.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: remove session cookie from backend request

src/main/resources/application-dev.yaml
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: fix bar client secret

.gitignore, README.md, build.gradle.kts, compose/application.yaml, compose/docker-compose.override.yaml, src/integrationTest/java/io/jaconi/morp/TestContainerSetup.java, src/integrationTest/resources/application.yaml, src/integrationTest/resources/morp/application.yaml, src/main/resources/application-dev.yaml, src/main/resources/application.yaml
Issue URL:
-
-
<hr />
❤️ Thank you!
=> refactor: Reworked handling of git-ignored secret.properties

build.gradle.kts
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: build native image only on x86_64 architecture

src/integrationTest/java/io/jaconi/morp/SeleniumIT.java, src/integrationTest/java/io/jaconi/morp/TruncatedRecordingFileFactory.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: shorten file names for selenium video recording

README.md, secret.properties.tpl
Issue URL:
-
-
<hr />
❤️ Thank you!
=> dev: pull secrets from 1Password

compose/docker-compose.yaml, src/main/java/io/jaconi/morp/oauth/ClientRegistrationActuator.java, src/main/resources/application.yaml, src/test/java/io/jaconi/morp/oauth/ClientRegistrationActuatorTest.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> feat: actuator endpoint for oauth client registry

README.md
Issue URL:
-
-
<hr />
❤️ Thank you!
=> docs: Added actuator endpoints to README

compose/application.yaml, src/main/java/io/jaconi/morp/MorpApplication.java, src/main/java/io/jaconi/morp/tenant/DynamicServerAuthenticationEntryPoint.java, src/main/java/io/jaconi/morp/tenant/TenantExtractor.java, src/main/java/io/jaconi/morp/tenant/TenantGatewayTagsProvider.java, src/main/java/io/jaconi/morp/tenant/TenantWebFluxTagsContributor.java, src/test/java/io/jaconi/morp/MorpApplicationTests.java, src/test/java/io/jaconi/morp/tenant/TenantExtractorTest.java, src/test/java/io/jaconi/morp/tenant/TenantGatewayTagsProviderTest.java, src/test/java/io/jaconi/morp/tenant/TenantWebFluxTagsContributerTest.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> feat: add tenant as optional metric dimension

build.gradle.kts, src/integrationTest/java/io/jaconi/morp/ActuatorIT.java, src/integrationTest/java/io/jaconi/morp/TestContainerSetup.java, src/main/java/io/jaconi/morp/SecurityConfiguration.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: disable CSRF

src/main/java/io/jaconi/morp/oauth/ClientRegistrationActuator.java
=> fix: potential NPE

.github/workflows/deploy-docs.yml
=> docs: always deploy latest docs

src/main/java/io/jaconi/morp/DebugController.java, src/main/java/io/jaconi/morp/filters/TenantExtractionFilter.java, src/main/java/io/jaconi/morp/oauth/MorpReactiveOAuth2UserService.java, src/main/java/io/jaconi/morp/oauth/MorpReactiveOidcUserService.java, src/test/java/io/jaconi/morp/filters/RemoveSessionCookieFilterTest.java, src/test/java/io/jaconi/morp/oauth/MorpReactiveOAuth2UserServiceTest.java, src/test/java/io/jaconi/morp/oauth/MorpReactiveOidcUserServiceTest.java
=> fix: code smells

src/main/java/io/jaconi/morp/tenant/TenantService.java, src/test/java/io/jaconi/morp/MorpApplicationTests.java, src/test/java/io/jaconi/morp/RoutingTest.java, src/test/java/io/jaconi/morp/tenant/DynamicServerAuthenticationEntryPointTest.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: minor code smells

README.md
=> docs: fix shield

.github/workflows/continuous.yaml
- adding skyk scanning to workflow
-
<hr />
❤️ Thank you!
=> ci(gh-actions): add Snyk scanning to continuous integration workflows

mkdocs/docs/user-guide/dns-rebind-protection.md
List in documentation is missing a preceding newline and therefore not rendered as a list.
List in documentation has a preceding newline and therefore rendered as a list.
=> docs: fix list

commitlint.config.js
Issue URL:
-
-
<hr />
❤️ Thank you!
=> ci: set commit message line length to infinity

build.gradle.kts, src/main/java/io/jaconi/morp/SecurityConfiguration.java
Issue URL:
-
-
<hr />
❤️ Thank you!
=> fix: remove Spring Security deprecations

src/integrationTest/java/io/jaconi/morp/SeleniumIT.java, src/main/java/io/jaconi/morp/oauth/ClientRegistrationFetcher.java
=> refactor: remove deprecated code

src/integrationTest/java/io/jaconi/morp/SeleniumIT.java, src/integrationTest/java/io/jaconi/morp/TestContainerSetup.java, src/integrationTest/resources/morp/application.yaml
Custom ports are used during integration tests.
The default ports are used during integration tests.
=> test: use default ports

src/integrationTest/java/io/jaconi/morp/SeleniumIT.java
=> test: use latest Chrome / Chromium

.github/workflows/continuous.yaml, .github/workflows/release.yaml
=> ci: update node

src/integrationTest/java/io/jaconi/morp/TestContainerSetup.java
=> test: start containers in parallel

.github/workflows/continuous.yaml
Issue URL:
-
-
<hr />
❤️ Thank you!
=> ci: replace deprecated Gradle actions

.github/workflows/continuous.yaml, .github/workflows/release.yaml, Dockerfile, build.gradle.kts
Issue URL:
-
-
<hr />
❤️ Thank you!
=> build: update to Java 21
